language: python	
python:	
  - "3.6"	

before_install:
  - export DBT_PROFILES_DIR=$(pwd)

install:	
  - pip install -U pip	
  - pip install -r requirements.txt	
  - pip install dbt==0.13.1	

script:	
  cd condor-transform && dbt test	